# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bbc7d9f9-dd16-45d3-a2a4-90e34c3efd20";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bbc7d9f9-dd16-45d3-a2a4-90e34c3efd20".device = "/dev/disk/by-uuid/bbc7d9f9-dd16-45d3-a2a4-90e34c3efd20";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/80D7-94A2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-dd68e6d0-e8fd-4445-9645-960caa375329"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
